name: Deploy to IIS

on:
  push:
    branches:
      - master  # or specify your main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # adjust to your project's version

    - name: Build and publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to IIS
      uses: jexus/webpi@v1
      with:
        package: ./publish
        websiteName: 'OnlineBuySellStore_UI'  # specify your IIS website name
        protocol: 'https'  # or 'http' depending on your server configuration
        serverUrl: 'https://theroyalblue.pk'  # specify your server URL
        username: ${{ secrets.IIS_USERNAME }} # add your IIS username to GitHub Secrets
        password: ${{ secrets.IIS_PASSWORD }}  # add your IIS password to GitHub Secrets
