name: Deploy to IIS

on:
  push:
    branches:
      - master  # Adjust branch as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'  # Adjust to match your project's SDK version

    - name: Restore dependencies and build
      run: |
        dotnet restore
        dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to IIS
      uses: DevLabs-UG/.Net-IIS-Deploy@v1
      with:
        WebsiteName: 'OnlineBuySellStore_UI'  # Name of your website in IIS
        PublishPath: './publish'  # Path to the published files
        IISPath: 'IIS:\Sites\OnlineBuySellStore_UI'  # IIS path to your website
        Server: '43.205.229.212'  # IP or hostname of your IIS server
        Username: ${{ secrets.IIS_USERNAME }}  # Credentials for accessing IIS
        Password: ${{ secrets.IIS_PASSWORD }}  # Store these in GitHub Secrets

